services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always

    environment:
      POSTGRES_DB: event_reservation_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always

    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always

    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    container_name: event-reservation-api
    restart: always

    depends_on:
      - postgres
      - redis
      - rabbitmq

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

volumes:
  postgres-data: