  feature/auth-service-tests[m
  feature/authentication-and-security[m
  feature/authentication-register[m
  feature/dto[m
  feature/entities[m
  feature/event-module[m
  feature/event-tests[m
  feature/exception-handling[m
  feature/images-readme[m
  feature/login-jwt[m
* [32mfeature/max-active-reservations[m
  feature/project-structure[m
  feature/redis-integration[m
  feature/repository-layer[m
  feature/reservation[m
  feature/reservation-concurrency-control[m
  feature/reservation-lifecycle[m
  feature/reservation-tests[m
  feature/seat-reservation-tests[m
  feature/security-integration-tests[m
  main[m
  refactor/auth-and-logging[m
  switch[m
