apiVersion: v1
kind: ConfigMap
metadata:
  name: event-api-config

data:
  POSTGRES_DB: event_reservation_api_db

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/event_reservation_api_db

  SPRING_DATA_REDIS_HOST: redis-service
  SPRING_DATA_REDIS_PORT: "6379"

  SPRING_RABBITMQ_HOST: rabbitmq-service
  SPRING_RABBITMQ_PORT: "5672"